version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - infra
      - p2-later
    groups:
      cargo-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - infra
      - p2-later
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
