//! Card definitions for Eldritch.
//!
//! Two layers:
//!
//! - **Metadata** — what's printed on a card (name, class, cost,
//!   traits, skill icons, …). Lives in [`types::CardMetadata`].
//!   Generated by the [`card-data-pipeline`] CLI from the pinned
//!   `ArkhamDB` snapshot at `data/arkhamdb-snapshot/`. The generated
//!   constants live in [`generated`]; access them via [`all`] or
//!   [`by_code`].
//!
//! - **Effects** — what a card *does* during play. Hand-written, one
//!   submodule per card under [`impls`]. The DSL handles common
//!   patterns; weird cards get a Rust trait impl.
//!
//! A card is *playable* iff it has an effect implementation. The
//! [`is_playable`] check is what the deck importer (Phase 9) uses to
//! refuse decks containing unimplemented cards.
//!
//! [`card-data-pipeline`]: ../../card_data_pipeline/index.html

use std::sync::OnceLock;

pub mod generated;
pub mod impls;
pub mod types;

pub use types::{CardMetadata, CardType, Class, SkillIcons, Slot};

/// All card metadata in the Eldritch corpus, lazily initialized on
/// first access. Sorted by [`CardMetadata::code`].
pub fn all() -> &'static [CardMetadata] {
    static ALL: OnceLock<Vec<CardMetadata>> = OnceLock::new();
    ALL.get_or_init(generated::all_cards).as_slice()
}

/// Look up a card by its `ArkhamDB` code. O(log n) via binary search.
#[must_use]
pub fn by_code(code: &str) -> Option<&'static CardMetadata> {
    all()
        .binary_search_by(|c| c.code.as_str().cmp(code))
        .ok()
        .map(|i| &all()[i])
}

/// Look up a card's hand-implemented abilities by code. Returns
/// `None` for unimplemented cards. Re-exported from
/// [`impls::abilities_for`].
#[must_use]
pub fn abilities_for(code: &str) -> Option<Vec<game_core::dsl::Ability>> {
    impls::abilities_for(code)
}

/// Whether a card has an effect implementation and can therefore be
/// taken into a scenario. Derived from [`abilities_for`] so the two
/// queries can never go out of sync. Cards without an implementation
/// still appear in [`all`] (deckbuilding tools list them) but are
/// refused by the deck-import gate.
#[must_use]
pub fn is_playable(code: &str) -> bool {
    abilities_for(code).is_some()
}

#[cfg(test)]
mod tests {
    use super::{all, by_code, is_playable, CardType, Class};

    #[test]
    fn corpus_is_sorted_by_code() {
        let cards = all();
        let mut prev = "";
        for c in cards {
            assert!(
                c.code.as_str() > prev,
                "cards must be sorted unique by code; saw {prev:?} then {:?}",
                c.code
            );
            prev = c.code.as_str();
        }
    }

    #[test]
    fn by_code_finds_a_known_card() {
        // 01030 is Magnifying Glass (the basic Seeker hand-slot tool
        // from the original Core Set). Used here as a sanity-check
        // that the generated corpus is non-empty and indexable.
        let mag = by_code("01030").expect("Magnifying Glass should exist");
        assert_eq!(mag.name, "Magnifying Glass");
        assert_eq!(mag.class, Class::Seeker);
        assert_eq!(mag.card_type, CardType::Asset);
    }

    #[test]
    fn by_code_returns_none_for_unknown() {
        assert!(by_code("99999").is_none());
    }

    #[test]
    fn dsl_pair_is_playable() {
        // PR-I lands Holy Rosary (01059) and Working a Hunch (01037).
        // Magnifying Glass needs a per-skill-test scope DSL extension
        // (its bonus is "while investigating", not flat). Hyperawareness
        // (01034) and Deduction (01039) need activated/triggered DSL
        // primitives — both come in PR-J as Rust-impl placeholders.
        assert!(is_playable("01037"));
        assert!(is_playable("01059"));
    }

    #[test]
    fn unimplemented_cards_are_not_playable() {
        // Magnifying Glass (01030), Hyperawareness (01034), Deduction
        // (01039) all blocked on DSL extensions — not yet playable.
        assert!(!is_playable("01030"));
        assert!(!is_playable("01034"));
        assert!(!is_playable("01039"));
        // Phase-2 doesn't touch most of the corpus.
        assert!(!is_playable("01001")); // Roland Banks
        assert!(!is_playable("99999")); // unknown code
    }

    #[test]
    fn abilities_for_returns_some_for_implemented() {
        for code in ["01037", "01059"] {
            let abilities = super::abilities_for(code)
                .unwrap_or_else(|| panic!("expected abilities for {code}"));
            assert!(
                !abilities.is_empty(),
                "abilities for {code} should be non-empty"
            );
        }
    }

    #[test]
    fn abilities_for_returns_none_for_unimplemented() {
        assert!(super::abilities_for("99999").is_none());
    }
}
