//! Card definitions for Eldritch.
//!
//! Cards live here as Rust source — both DSL declarations for the common
//! patterns and hand-written trait impls for the weird ones. Card metadata
//! and stubs are generated by `card-data-pipeline` from the pinned
//! `data/arkhamdb-snapshot/` snapshot.
