//! Card definitions for Eldritch.
//!
//! Two layers:
//!
//! - **Metadata** — what's printed on a card (name, class, cost,
//!   traits, skill icons, …). Lives in [`types::CardMetadata`].
//!   Generated by the [`card-data-pipeline`] CLI from the pinned
//!   `ArkhamDB` snapshot at `data/arkhamdb-snapshot/`. The generated
//!   constants live in [`generated`]; access them via [`all`] or
//!   [`by_code`].
//!
//! - **Effects** — what a card *does* during play. Hand-written, one
//!   submodule per card under [`impls`]. The DSL handles common
//!   patterns; weird cards get a Rust trait impl.
//!
//! A card is *playable* iff it has an effect implementation. The
//! [`is_playable`] check is what the deck importer (Phase 9) uses to
//! refuse decks containing unimplemented cards.
//!
//! [`card-data-pipeline`]: ../../card_data_pipeline/index.html

use std::sync::OnceLock;

pub mod generated;
pub mod impls;
pub mod types;

pub use types::{CardMetadata, CardType, Class, SkillIcons, Slot};

/// All card metadata in the Eldritch corpus, lazily initialized on
/// first access. Sorted by [`CardMetadata::code`].
pub fn all() -> &'static [CardMetadata] {
    static ALL: OnceLock<Vec<CardMetadata>> = OnceLock::new();
    ALL.get_or_init(generated::all_cards).as_slice()
}

/// Look up a card by its `ArkhamDB` code. O(log n) via binary search.
#[must_use]
pub fn by_code(code: &str) -> Option<&'static CardMetadata> {
    all()
        .binary_search_by(|c| c.code.as_str().cmp(code))
        .ok()
        .map(|i| &all()[i])
}

/// Whether a card has an effect implementation and can therefore be
/// taken into a scenario. Cards without an implementation appear in
/// [`all`] (so deckbuilding tools can list them) but are refused by
/// the deck-import gate.
#[must_use]
pub fn is_playable(code: &str) -> bool {
    let impls = impls::implementations();
    debug_assert!(
        impls.windows(2).all(|w| w[0] < w[1]),
        "impls::implementations() must return a sorted, deduplicated slice for binary_search to be valid"
    );
    impls.binary_search(&code).is_ok()
}

#[cfg(test)]
mod tests {
    use super::{all, by_code, is_playable, CardType, Class};

    #[test]
    fn corpus_is_sorted_by_code() {
        let cards = all();
        let mut prev = "";
        for c in cards {
            assert!(
                c.code.as_str() > prev,
                "cards must be sorted unique by code; saw {prev:?} then {:?}",
                c.code
            );
            prev = c.code.as_str();
        }
    }

    #[test]
    fn by_code_finds_a_known_card() {
        // 01030 is Magnifying Glass (the basic Seeker hand-slot tool
        // from the original Core Set). Used here as a sanity-check
        // that the generated corpus is non-empty and indexable.
        let mag = by_code("01030").expect("Magnifying Glass should exist");
        assert_eq!(mag.name, "Magnifying Glass");
        assert_eq!(mag.class, Class::Seeker);
        assert_eq!(mag.card_type, CardType::Asset);
    }

    #[test]
    fn by_code_returns_none_for_unknown() {
        assert!(by_code("99999").is_none());
    }

    #[test]
    fn no_cards_are_playable_yet() {
        // Phase-2 PR-G ships the framework; the 5 Phase-2 card impls
        // land in PR-I onward. Until then nothing is playable.
        assert!(!is_playable("01030"));
        assert!(!is_playable("01059"));
    }
}
